[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mymodule"
version = "1.0"
description = "A simple code using Py_ABS function of Python/C API."
requires-python = ">=3.9"
